import { readFileSync, writeFileSync } from "node:fs";
const text = readFileSync(new URL("../docs/sumber.md", import.meta.url), "utf8");
const output = `// Generated by scripts/sync-source.mjs from docs/sumber.md.\nexport const sourceText = ${JSON.stringify(text)};\n`;
const target = new URL("../src/source-text.ts", import.meta.url);
if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== output) throw Error("Jalankan node scripts/sync-source.mjs setelah mengubah sumber.md.");
} else writeFileSync(target, output);
